[project]
name = "server"
version = "0.0.0"
description = "My Universe"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.3",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.14.1",
]
